default: &default
#  adapter: sqlite3
#  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#  timeout: 5000
  adapter: mysql2
  host: 127.0.0.1
  username: root
  password: <%= ENV['PASS'] %>
  encoding: utf8

development:
  <<: *default
  database: development
#  database: db/development.sqlite3

test:
  <<: *default
  database: test
#  database: db/test.sqlite3

production:
  <<: *default
  database: development
#  database: db/production.sqlite3
